services:
- type: web
  name: wordpress
  env: docker
  plan: starter
  autoDeploy: false
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 5
  envVars:
  - key: WORDPRESS_CONFIG_EXTRA
    value: |
      upload_max_filesize = 1.8G;
      post_max_size = 2.2G;
  envVars:
  - key: WORDPRESS_DB_HOST
    fromService:
      name: mysql-wordpress
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: mysql-wordpress
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: mysql-wordpress
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: mysql-wordpress
      type: pserv
      envVarKey: MYSQL_PASSWORD
- type: pserv
  name: mysql-wordpress
  repo: https://github.com/render-examples/mysql.git
  env: docker
  plan: starter
  autoDeploy: false
  disk:
    name: mysql-wordpress
    mountPath: /var/lib/mysql
    sizeGB: 5
  envVars:
  - key: MYSQL_DATABASE
    value: wp_db
  - key: MYSQL_USER
    value: wp_user
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
